package net.rdyonline.android_training.orm;

import java.util.List;
import net.rdyonline.android_training.orm.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import net.rdyonline.android_training.orm.dao.RoomDao;
import net.rdyonline.android_training.orm.dao.TimeslotDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ROOM.
 */
public class Room implements java.io.Serializable {

    private Long id;
    private String name;
    private Long capacity;
    private Long conference;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient RoomDao myDao;

    private List<Timeslot> timeslotList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Room() {
    }

    public Room(Long id) {
        this.id = id;
    }

    public Room(Long id, String name, Long capacity, Long conference) {
        this.id = id;
        this.name = name;
        this.capacity = capacity;
        this.conference = conference;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRoomDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getCapacity() {
        return capacity;
    }

    public void setCapacity(Long capacity) {
        this.capacity = capacity;
    }

    public Long getConference() {
        return conference;
    }

    public void setConference(Long conference) {
        this.conference = conference;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Timeslot> getTimeslotList() {
        if (timeslotList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TimeslotDao targetDao = daoSession.getTimeslotDao();
            List<Timeslot> timeslotListNew = targetDao._queryRoom_TimeslotList(id);
            synchronized (this) {
                if(timeslotList == null) {
                    timeslotList = timeslotListNew;
                }
            }
        }
        return timeslotList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetTimeslotList() {
        timeslotList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
